version: '3.1'

services:
  seed:
    image: colinmollenhour/mariadb-galera-swarm:latest
    environment:
      - XTRABACKUP_PASSWORD_FILE=/run/secrets/xtrabackup_password
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_password
      - MYSQL_DATABASE=wordpress
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
      - NODE_ADDRESS=eth0
    command: seed
    volumes:
      - mysql-data:/var/lib/mysql
    secrets:
      - xtrabackup_password
      - mysql_password
      - mysql_root_password
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
  node:
    image: colinmollenhour/mariadb-galera-swarm:latest
    environment:
      - XTRABACKUP_PASSWORD_FILE=/run/secrets/xtrabackup_password
      - NODE_ADDRESS=eth0
    command: node seed,node
    deploy:
      replicas: 0
      update_config:
        parallelism: 1
        delay: 30s
      restart_policy:
        condition: on-failure
    secrets:
      - xtrabackup_password
  memcached:
    image: memcached
    command: memcached -m 512m
    deploy:
      replicas: 2
  wordpress:
    image: withinboredom/scalable-wordpress
    environment:
      - WORDPRESS_DB_HOST=node
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD_FILE=/run/secrets/mysql_password
      - WORDPRESS_AUTH_KEY_FILE=/run/secrets/AUTH_KEY
      - WORDPRESS_SECURE_AUTH_KEY_FILE=/run/secrets/SECURE_AUTH_KEY
      - WORDPRESS_LOGGED_IN_KEY_FILE=/run/secrets/LOGGED_IN_KEY
      - WORDPRESS_NONCE_KEY_FILE=/run/secrets/NONCE_KEY
      - WORDPRESS_AUTH_SALT_FILE=/run/secrets/AUTH_SALT
      - WORDPRESS_SECURE_AUTH_SALT_FILE=/run/secrets/SECURE_AUTH_SALT
      - WORDPRESS_LOGGED_IN_SALT_FILE=/run/secrets/LOGGED_IN_SALT
      - WORDPRESS_NONCE_SALT_FILE=/run/secrets/NONCE_SALT
      - PLUGINS=jetpack@latest,batcache@latest
    secrets:
      - mysql_password
      - AUTH_KEY
      - SECURE_AUTH_KEY
      - LOGGED_IN_KEY
      - NONCE_KEY
      - AUTH_SALT
      - SECURE_AUTH_SALT
      - LOGGED_IN_SALT
      - NONCE_SALT
    deploy:
      replicas: 0
      labels:
        - "traefik.port=80"
  traefik:
    image: traefik
    ports:
      - 80:80
      - 8000:8080
      - 443:433
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --docker --docker.swarmmode --docker.watch --web
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

volumes:
  mysql-data:
    driver: local

secrets:
  xtrabackup_password:
    file: .secrets/xtrabackup_password
  mysql_password:
    file: .secrets/mysql_password
  mysql_root_password:
    file: .secrets/mysql_root_password
  AUTH_KEY:
    file: .secrets/AUTH_KEY
  SECURE_AUTH_KEY:
    file: .secrets/SECURE_AUTH_KEY
  LOGGED_IN_KEY:
    file: .secrets/LOGGED_IN_KEY
  NONCE_KEY:
    file: .secrets/NONCE_KEY
  AUTH_SALT:
    file: .secrets/AUTH_SALT
  SECURE_AUTH_SALT:
    file: .secrets/SECURE_AUTH_SALT
  LOGGED_IN_SALT:
    file: .secrets/LOGGED_IN_SALT
  NONCE_SALT:
    file: .secrets/NONCE_SALT
