version: '3.1'

services:
  node:
    image: colinmollenhour/mariadb-galera-swarm:latest
    environment:
      - XTRABACKUP_PASSWORD_FILE=/run/secrets/xtrabackup_password
      - NODE_ADDRESS=eth0
    command: node seed,node
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 30s
      restart_policy:
        condition: on-failure
    secrets:
      - xtrabackup_password
  memcached:
    image: memcached
    command: memcached -m 512m
    deploy:
      replicas: 2
  wordpress:
    image: withinboredom/scalable-wordpress:4.7.3-apache
    environment:
      - WORDPRESS_DB_HOST=node
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD_FILE=/run/secrets/mysql_password
      - WORDPRESS_AUTH_KEY_FILE=/run/secrets/AUTH_KEY
      - WORDPRESS_SECURE_AUTH_KEY_FILE=/run/secrets/SECURE_AUTH_KEY
      - WORDPRESS_LOGGED_IN_KEY_FILE=/run/secrets/LOGGED_IN_KEY
      - WORDPRESS_NONCE_KEY_FILE=/run/secrets/NONCE_KEY
      - WORDPRESS_AUTH_SALT_FILE=/run/secrets/AUTH_SALT
      - WORDPRESS_SECURE_AUTH_SALT_FILE=/run/secrets/SECURE_AUTH_SALT
      - WORDPRESS_LOGGED_IN_SALT_FILE=/run/secrets/LOGGED_IN_SALT
      - WORDPRESS_NONCE_SALT_FILE=/run/secrets/NONCE_SALT
      - MEMCACHED_HOST=tasks.memcached
      - PLUGINS=jetpack@latest,batcache@latest,wp-maintenance-mode@latest,cookie-notice,disqus-comment-system
    secrets:
      - mysql_password
      - AUTH_KEY
      - SECURE_AUTH_KEY
      - LOGGED_IN_KEY
      - NONCE_KEY
      - AUTH_SALT
      - SECURE_AUTH_SALT
      - LOGGED_IN_SALT
      - NONCE_SALT
    deploy:
      replicas: 2
      labels:
        - "traefik.port=80"
        - "traefik.frontend.rule=Host:withinboredom.info,www.withinboredom.info"
        - "traefik.backend.circuitbreaker.expression=NetworkErrorRatio() > 0.5"
        - "traefik.frontend.passHostHeader=true"
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
  traefik:
    image: withinboredom/scalable-wordpress:traefik-camembert
    ports:
      - 80:80
      - 8000:8080
      - 443:433
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --docker --docker.swarmmode --docker.watch --web
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

secrets:
  xtrabackup_password:
    file: .secrets/xtrabackup_password
  mysql_password:
    file: .secrets/mysql_password
  mysql_root_password:
    file: .secrets/mysql_root_password
  AUTH_KEY:
    file: .secrets/AUTH_KEY
  SECURE_AUTH_KEY:
    file: .secrets/SECURE_AUTH_KEY
  LOGGED_IN_KEY:
    file: .secrets/LOGGED_IN_KEY
  NONCE_KEY:
    file: .secrets/NONCE_KEY
  AUTH_SALT:
    file: .secrets/AUTH_SALT
  SECURE_AUTH_SALT:
    file: .secrets/SECURE_AUTH_SALT
  LOGGED_IN_SALT:
    file: .secrets/LOGGED_IN_SALT
  NONCE_SALT:
    file: .secrets/NONCE_SALT
