version: '3.1'

services:
  memcached:
    image: memcached
    command: memcached -m 512m
    deploy:
      replicas: 2
      resources:
        reservations:
          cpus: '0.2'
          memory: '512m'
        limits:
          cpus: '1.0'
          memory: '712m'
